apiVersion: v1
kind: Service
metadata:
  name: static-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: static-web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
